### PR TITLE
feat(leaves): New list component.

### PR DESCRIPTION
**Pull request by Lattay**
Hi,

I'd like to get some feedback on this proposal of list component.

What is implemented:
- The component shows a paged list of item with a cursor.
- The cursor can be moved with arrow keys and hjkl.
- The current element can be selected with space.
- The list of elements can be retrieve from the model.
- A filter can be applied (the example demonstrate this with a Text_input) to temporarily hide elements.

What is not implemented:
- It would be nice to use customizable key bindings instead of hard coded one (based #22 or something similar).
- There is probably room for improvement on the styling front

Also, I couldn't get the dev version of minttea to build (independantly of my modifications, something wrong with the versions of Riot and libc and other I think), so I only tested the component and the example with commit 87c80723fb83 (that is release 0.0.2).
This is the main reason why I consider this to be WIP.

### CODE REVIEW

**Comment by leostera** [comment]
Thanks for opening the PR @Lattay! :sparkles: – I'd really appreciate if you can record a demo for this new component in an example so its obvious what it does and we can feature it in the examples index page.

To record you can install [VHS](https://github.com/charmbracelet/vhs) and run `vhs demo.tape`, assuming you copied over some of the `demo.tape` files from the other examples and adjusted them a little.

**Comment by Lattay** [comment]
Ok, so... now that I have updated to riot 0.0.8 and stuff, my example is broken in a very weird way. It makes me thinh about a race condition somewhere because it is pretty random:
- sometime the program returns immediately before writing anything
- sometime it prints nothing but hangs
- sometime it prints the first view and hangs
- one time it ran normally (I think)

Investigating that now...

**Comment by Lattay** [comment]
Hi,

The previously mentionned bug seems to be solved in 0.0.3 version.

Here is a demo of the list component.

demo

Note that for some reason (unrelated to the component) the "Pick your favorite food" line is not cleared properly before printing the selection at the end.

**Comment by leostera** [comment]
Hi @Lattay! This looks fantastic ✨ – thanks a million for contributing! Merging it now.

**Pull request merged**
