### PR TITLE
fix: apply padding before rendering of core text

### PR DESCRIPTION
**Pull request by wonbyte**
Apply `padding` before rendering core text.

Addresses issue #4

### CODE REVIEW

**Comment by wonbyte** [comment]
@leostera took a shot at this one. Let me know what I need to fix :)

**Comment by leostera** [comment]
Ooh excellent! ✨ 

It would be awesome if you can use these styles in one of the examples (or make a new example) so its easy to visualize that the changes work by looking at the demo gif.

Let me know if I can help 🙏🏼

**Comment by wonbyte** [comment]
@leostera 👀

**Comment by leostera** [comment]
Hi @wonbyte and sorry for the delays! I think we will want to look into demoing this in combination with @jmcavanillas's work on escape-code aware string wrapping lib [shape-the-term](https://github.com/jmcavanillas/shape-the-term).

I'll merge it as is for now and we can improve later on.

Thanks for the contribution ✨ 🙌🏼

**Pull request merged**
