### PR TITLE
feat(progress): option to toggle percentage display

### PR DESCRIPTION
**Pull request by wesleimp**

### CODE REVIEW

**Comment by leostera** [comment]
Hi @wesleimp and thanks a million for opening this PR! ✨ – would you mind re-recording the demo gif so its easy for us to see what this change looks like?

Otherwise it looks great, so as soon as the GIF is there, I'd be happy to merge.

**Comment by wesleimp** [comment]
@leostera Here it is. I've modified the progress example

https://github.com/leostera/minttea/assets/42675056/840257fe-ab6e-49af-9499-5b34e75d87d6

**Comment by leostera** [comment]
Awesome! Please include it in the PR and we'll be good for merging.

**Comment by wesleimp** [comment]
@leostera I think now it's ready to go

**Pull request merged**
